baseurl = "https://dominikfrick.github.io/"
languageCode = "en-us"
title = "The Title"
theme = "beautifulhugo"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  logo = "img/sunflower.jpg"
  subtitle = "Some subtitle"

[Author]
  name = "Some Person"
#  email = "youremail@domain.com"
#  facebook = "username"
#  github = "username"
#  twitter = "username"
#  linkedin = "pub/username/X/YYY/ZZZ"
#  stackoverflow = "XXXXXXX/username"
#  soundcloud = "username"
#  wikipedia = "username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2